# Site settings
title: Численные методы
baseurl: "/numeric-methods"
url: "http://vstu-physics.github.io"
timezone: Europe/Volgograd
github_username:  vstu-physics

# Build settings
markdown: kramdown
permalink: /:categories/:title
